server {
  listen 80;
  server_name localhost;

  root   /usr/share/nginx/html;
  index  index.html;

  
  # 1) 先讓靜態資源走正常路徑
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|ttf|woff2?)$ {
    try_files $uri =404;
  }

  # 2) 所有其他請求都 fallback 回 index.html，由前端 router 決定要顯示哪一頁
  location / {
    try_files $uri $uri/ /index.html;
  }
}
